version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/remind-bot-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: myuulove11
    ports:
      - '3316:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_vol:/var/lib/mysql
volumes:
  mysql_vol:
    driver: local
